In [2]:
import numpy as np
import pandas as pd

In [7]:
#创建一个大小为10的空向量
print(np.empty(10))
print(np.zeros(10))
print(np.full((2,5),5.0))
#一.python中的数据类型
#知识点：创建数组
# np.empty 构造一个大小为 shape 的未初始化数组,
# np.zeros 构造一个大小为 shape 的全0数组,
# np.ones 构造一个大小为 shape 的全1数组,
# np.ones 构造一个大小为 shape 的全1数组,
# np.full 构造一个大小为 shape 的用指定值填满的数组

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [31]:
#查看数组占用内存大小
#二.numpy数据基础
#每个数据元素字节的大小itemsize，nbytes总大小
# hint 每个元素点用内存大小乘以元素个数
sample4_1 = np.empty((3, 2), np.uint32)
sample4_2 = np.empty((3, 2), np.float16)
print(sample4_1.itemsize * sample4_1.size)
print(sample4_2.itemsize * sample4_2.size)

24
12


In [10]:
#查看numpy中add函数的用法
#三、Numpy数组的计算：通用函数
# 使用 np.info函数可以查询函数，类，模块的文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [11]:
#创建一个大小为10的空向量，将第5个值设为1
#一、理解Python种的数据类型
#二、NumPy数组基础
#知识点：创建数组、数组索引获取单个元素修改元素值
sample = np.zeros(10)
sample[4] = 1
print(sample)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#用10到49的序列构建一个向量
#一、理解Python种的数据类型
#二、NumPy数组基础
#知识点：主要是第二节的切分，不包含stop的值
sample2 = np.arange(10, 50) 
# arange 同样不包含stop的值。
print(sample2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#将一个数组变换倒序（最后一个元素成为第一个元素）
#二、NumPy数组基础
#知识点：数组切片
# hint  这里是python的切片[起：止：间隔]
# print(np.arange(10)[::1]) 正常输出
# print(np.arange(10)[0::1]) 与上面相同
# print(np.arange(10)[1::1]) 从第二个元素开始到最后一个
# print(np.arange(10)[1::-1]) 从第二个元素开始倒序输出
# print(np.arange(10)[::-2]) 从最后一个元素起，间隔一个输出
print(np.arange(10))
print(np.arange(10)[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [14]:
#用0-8这9个数构造一个3x3大小的矩阵
#二、NumPy数组基础
#知识点：数组变形
# reshape 可以允许有一个参数为-1 ，系统会依据元素个数进行换算
sample3 = np.arange(9).reshape((3, -1))
print(sample3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#从数组[1,2,0,0,4,0]中找出非0元素的下标
#六、比较、掩码、和布尔逻辑
#知识点：统计记录的个数布尔数组
print(np.nonzero([1, 2, 0, 0, 4, 0]))

(array([0, 1, 4], dtype=int64),)


In [16]:
#创建3x3的对角矩阵（没在书的范围里）
#一、理解Python种的数据类型
#知识点：多维数组
# identity 只能创建方阵，eye要灵活一些，可以创建NxM的矩阵，也可以控制对角线的位置
print(np.identity(3))
print(np.eye(3,3,0))  #默认第一个和第二个参数相等，第三个参数为对角线位置

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
#用随机数创建一个3x3x3的矩阵，(np.random.seed(0))
#一、理解Python种的数据类型
#知识点：多维数组、随机数
np.random.seed(0)
print(np.random.random((3, 3, 3)))

[[[0.5488135  0.71518937 0.60276338]
  [0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276]]

 [[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]
  [0.0871293  0.0202184  0.83261985]]

 [[0.77815675 0.87001215 0.97861834]
  [0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329]]]


In [43]:
#创建一个10x10的随机数矩阵，并找到最大值和最小值(np.random.seed(0))
#一、理解Python种的数据类型
#四、聚合：最小值、最大值和其他值
#知识点：多维数组、随机数、最大值、最小值
np.random.seed(0)
sample13 = np.random.random((10, 10))
print(sample13)
print(sample13.max(), np.min(sample13))

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787
  0.21038256 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676 0.16130952
  0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
  0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358 0.03918779
  0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145 0.26538949
  0.52324805 0

In [42]:
#创建一个大小为30的数组，并计算其算术平均值
#三、Numpy数组的计算：通用函数
#知识点：
# mean计算算术平均值 average 计算加权平均值np.average(np.arange(1, 11) , weights=np.arange(10, 0, -1))
print(np.random.random(30).mean())

0.5825186271316452


In [21]:
# 创建一个二维数组，边为1，其余为0 
# 1:-1,1:-1]表示切出了芯。
sample15 = np.ones((5, 5))
print(sample15)
sample15[1:-1, 1:-1] = 0
print(sample15)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#扩展给定数组的边界
# pad 函数 有几种mode
sample16 = np.ones((4,4))
print(np.pad(sample16, 1, mode='constant', constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
#指出下列表达式的结果是什么
#四、聚合：最小值、最大值和其他值
#知识点：
# nan的意思是Not a Number nan的类型是float64
print(0 * np.nan)  # nan  有nan参与的运算, 其结果也一定是nan
print(np.nan - np.nan) # nan
print(np.nan == np.nan) # False nan不是数，所以无法进行比较运算
print(np.nan > np.nan) # False
print(np.nan in {np.nan}) # True  nan在nan的字典中
print(0.3 == 3 * 0.1) # False  浮点数可以比大小，但相等要用math.isclose比较
import math
print(math.isclose(0.3, 3 * 0.1)) # True

nan
nan
False
False
True
False
True


In [24]:
#用1，2，3，4做为对角线的下移一行，来创建5x5的矩阵
# diag函数的第二个参数指定对角线的位置
print(np.diag([1, 2, 3, 4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
#创建一个类似国际象棋棋盘的8x8的矩阵
#一、理解Python种的数据类型
#二、NumPy数组基础
#七、花哨的索引
#知识点：索引修改元素值
sample19 = np.zeros((8, 8))
sample19[::2, ::2] = 1
sample19[1::2, 1::2] = 1
print(sample19)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [2]:
#随机给一个三行四列的数组，并求和（np.random.seed(0)）
#二、NumPy数组基础
#四、聚合：最小值、最大值和其他值
#知识点：
#NumPy中可用的聚合函数sum
np.random.seed(0)
M = np.random.random((3, 4))
print(M)
M.sum()

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


7.478282790980994

In [4]:
#随机机给一个五行五列的数组并且元素值乘10，打印数组，打印数组-元素的平均值/元素的方差
#二、NumPy数组基础
#三、Numpy数组的计算：通用函数
#四、聚合：最小值、最大值和其他值
#知识点：Numpy中可用的聚合函数 
sample22 = np.random.random((5,5))*10
print(sample22)
print((sample22 - sample22.mean()) / sample22.std()) # std 计算均方差

[[6.16933997 9.43748079 6.81820299 3.59507901 4.37031954]
 [6.97631196 0.60225472 6.66766715 6.7063787  2.10382561]
 [1.28926298 3.15428351 3.63710771 5.7019677  4.38601513]
 [9.88373838 1.02044811 2.08876756 1.61309518 6.53108325]
 [2.53291603 4.66310773 2.44425592 1.58969584 1.10375141]]
[[ 0.75471824  2.00938197  1.00382161 -0.23355982  0.06406082]
 [ 1.06452083 -1.38252748  0.94602978  0.96089143 -0.80606317]
 [-1.11877986 -0.40278451 -0.21742469  0.57529053  0.07008648]
 [ 2.1807036  -1.2219799  -0.81184406 -0.99445825  0.8935942 ]
 [-0.64133214  0.1764644  -0.67536942 -1.00344144 -1.18999914]]


In [58]:
#反转一维数组中大于3小于8的所有元素
#三、NumPy数组的计算：通用函数
#六、比较、掩码、和布尔逻辑
#知识点：NumPy实现的算术运算符、NumPy的通用函数
sample25 = np.arange(2, 12)
sample25[(sample25 >3) & (sample25 <8)] *= -1 # 使用& 表示 and
print(sample25)

[ 2  3 -4 -5 -6 -7  8  9 10 11]


In [60]:
#查找两个数组的交集?
print(np.intersect1d([1, 2, 3], [4, 2, 1]))

[1 2]


In [62]:
#创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1
#一、理解Python种的数据类型
#二、NumPy数组基础
#知识点：创建数组、索引修改元素值
s1=np.zeros(10)
s1[4]=1
s1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [65]:
#创建一个大小为10的数组并排序(np.random.seed(0))
#八、数组的排序
#知识点：排序
np.random.seed(0)
sample40 = np.random.randint(0, 9, 10)
sample40.sort()
print(sample40)

[0 2 3 3 3 4 5 5 7 7]


In [66]:
#对一个小数组用比np.sum快的方法求和?
#四、聚合：最小值、最大值和其他值
#知识点：求和
sample41 = np.arange(0,20)
print(np.add.reduce(sample41))

190


In [67]:
#比较两个随机数组是否相等
#四、聚合：最小值、最大值和其他值
#知识点：比较运算符和其对应的通用函数
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B) #默认在1e-05的误差范围内,比较两个array是不是每一元素都相等
print(equal)
equal = np.array_equal(A,B) # 比较两个数组是否相等
print(equal)

False
False


In [70]:
#创建一个大小为10的数组并把最大值设为0
#四、聚合：最小值、最大值和其他值
#知识点：NumPy中可用的聚合函数np.argmax 找出最大值的索引
np.random.seed(0)
sample45 = np.random.uniform(0,9,10)
print(sample45)
sample45[sample45.argmax()] =0
print(sample45)

[4.93932154 6.4367043  5.42487038 4.90394865 3.81289319 5.81304702
 3.9382849  8.02595701 8.67296484 3.45097367]
[4.93932154 6.4367043  5.42487038 4.90394865 3.81289319 5.81304702
 3.9382849  8.02595701 0.         3.45097367]


In [74]:
#矩阵的第一行减去算术平均值（np.random.seed(0)）
#四、聚合：最小值、最大值和其他值
np.random.seed(0)
sample58 = np.random.rand(3,3)*10
print(sample58)
print(np.subtract(sample58,np.mean(sample58,axis=1,keepdims=True)))

[[5.48813504 7.15189366 6.02763376]
 [5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761]]
[[-0.73441912  0.92933951 -0.19492039]
 [ 0.06739151 -1.14489232  1.07750081]
 [-3.2675378   1.2743201   1.9932177 ]]


In [78]:
#八、数组的排序(np.random.seed(0))
#知识点：是 argsort该函数返回的是原始数组排好序的索引值
#sort快速排序
np.random.seed(0)
sample59 = np.random.randint(0, 9, (3, 5))
print(sample59)
print(np.sort(sample59, axis=0))  # 全部都排序
print(np.argsort(sample59, axis=0))  # 给出的是位置
print(sample59[sample59[:, 1].argsort()])  # 按第二列排序

[[5 0 3 3 7]
 [3 5 2 4 7]
 [6 8 8 1 6]]
[[3 0 2 1 6]
 [5 5 3 3 7]
 [6 8 8 4 7]]
[[1 0 1 2 2]
 [0 1 0 0 0]
 [2 2 2 1 1]]
[[5 0 3 3 7]
 [3 5 2 4 7]
 [6 8 8 1 6]]


In [81]:
#从数组中找出给定值的最近似值
#三、NumPy数组的计算：通用函数
#知识点：
np.random.seed(0)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5448831829968969


In [85]:
# 如何创建一个5*5的矩阵，每行的数值都是从0到4？
#五、数组的计算：广播
#知识点：利用numpy数组的广播功能
array1=np.arange(5)
array2=np.zeros((5,5))
array=array1+array2
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [87]:
#如何找出数组np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])中第五个1出现的位置？
#八、数组的排序
#二、NumPy数组基础
#知识点：索引、排序
array=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
loc=np.argsort(array)[4]
loc

8

In [91]:
#如何把数组np.random.randint(1,10(3,3))按照数组最后一列的数值进行排序？(np.random.seed(0))
#八、数组的排序
#七、花哨的索引
#知识点：
np.random.seed(0)
array=np.random.randint(1,10,(3,3))
order=np.argsort(array[:,-1])
array=array[order,:]
array

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [6]:
#如何将数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)垂直堆叠？
#二、NumPy数组基础
#知识点：数组拼接
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
array=np.hstack((a,b))
#a = np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)
#array=np.concatenate((a,b),axis=1)
array


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
#一个四维的数组，以后两维度为单位，计算它们的和，比如一个1*2*3*4的数组，则以后面3*4维度为单位，输出1*2的sum
#四、聚合：最小值、最大值和其他值
#七、花哨的索引
#（np.random.seed(0)）
np.random.seed(0)
A = np.random.randint(0,10,(1,2,3,4))
A.reshape(A.shape[:-2] + (-1,))
sum1 = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum1)


[[54 77]]


In [17]:
#二维矩阵与三维矩阵如何相乘（A矩阵元素都为1，B矩阵元素都为2）
#五、数组的计算：广播
A = np.ones((3,3,2))
B = 2*np.ones((3,3))
print (A * B[:,:,None])

[[[2. 2.]
  [2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]
  [2. 2.]]]


In [23]:
#用0~11的数字生成(3,4)的数组命名为A,查看A的维度；查看A中元素的数据类型。
#一、理解Python中的数据类型
#二、NumPy数组基础
A=np.arange(12).reshape(3,4)
A
A.shape#查看维度
A.dtype#查看元素数据类型

dtype('int32')

In [25]:
#创建一个全0的（4,4）的数组B; 创建一个内容全1的(3,2)数组C。
#二、NumPy数组基础
B=np.zeros((4,4))
B
C=np.ones((3,2))
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
#用0~19的数，创建一个4*5的数组D，计算每一列的和；计算每一行的最小值.
#二、NumPy数组基础
#四、聚合：最小值、最大值和其他值
D=np.arange(20).reshape(4,5)
D
D.sum(axis=0)
D.min(axis=1)

array([ 0,  5, 10, 15])

In [30]:
#用0~11的数字生成一个数组E,计算每个元素的平方；取出索引为4的元素；取出索引为3至5之间的元素。
#二、NumPy数组基础
#三、Numpy数组的计算：通用函数
E=np.arange(9)
E
E**2
E[4]
E[3:5]

array([3, 4])

In [33]:
#随机生成2个3*3的数组F和G，将F和G进行垂直合并形成FG;将F和G进行水平合并形成GF。
#（np.random.seed(0)）
#二、NumPy数组基础
np.random.seed(0)
F=np.random.random((3,3))
F
G=np.random.random((3,3))
G
FG=np.vstack((F,G))
FG
GF=np.hstack((G,F))
GF

array([[0.38344152, 0.79172504, 0.52889492, 0.5488135 , 0.71518937,
        0.60276338],
       [0.56804456, 0.92559664, 0.07103606, 0.54488318, 0.4236548 ,
        0.64589411],
       [0.0871293 , 0.0202184 , 0.83261985, 0.43758721, 0.891773  ,
        0.96366276]])

In [35]:
#创建一个3行2列的零矩阵命名为H,将H的3行2列的值置成1。
#七、花哨的索引
H=np.zeros((3,2))
H[2][1]=1
H

array([[0., 0.],
       [0., 0.],
       [0., 1.]])

In [3]:
#假设数组 a 的维度为 3X4，数组 b 的维度为 1X4 ，则使用以下迭代器（数组 b 被广播到 a 的大小）。
#十、迭代数组
#五、数组的计算：广播
#知识点：迭代，广播
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )
    

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

In [4]:
#bitwise_and() 函数对数组中整数的二进制形式执行位与运算。那么13 和 17 的二进制形式是？13 和 17 的位与是？
#十一、位运算
#知识点：对数组元素执行位与操作
print ('13 和 17 的二进制形式：')
a,b = 13,17
print (bin(a), bin(b))
print ('\n')
 
print ('13 和 17 的位与：')
print (np.bitwise_and(13, 17))

13 和 17 的二进制形式：
0b1101 0b10001


13 和 17 的位与：
1


In [6]:
#numpy.ndarray.byteswap() 函数将 ndarray 中每个元素中的字节进行大小端转换。
#十二、字接交换
a = np.array([1,  256,  8755], dtype = np.int16)  
print ('以十六进制表示内存中的数据：')
print (map(hex,a))
# byteswap() 函数通过传入 true 来原地交换 
print ('调用 byteswap() 函数：')
print (a.byteswap(True))
print ('十六进制形式：')
print (map(hex,a))
# 我们可以看到字节已经交换了

以十六进制表示内存中的数据：
调用 byteswap() 函数：
[  256     1 13090]
十六进制形式：
