# 数组的转置和轴对换

In [3]:
# 以多维数组为例，如：（2， 2， 4）表示 2个2X4矩阵，
# 可以理解为（2[0], 2[1], 2[2]）,其中[0]表示0轴。

In [4]:
import numpy as np  
arr=np.arange(16).reshape(2,2,4)  

In [5]:
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
# 1、transpose（1,0,2）：表示将（2[0], 2[1], 2[2]）转换为（2[1], 2[0], 2[2]）。
# 简单理解就是，将不同位置元素替换掉。

# 比如：arr[0, 0, 0]，第一位和第二位转换后，仍是arr[0, 0, 0]。
# arr[0 , 1, 0] = 4, 转换后为 arr[1, 0, 0] = 8。同理arr[1, 0 , 0]转换为 arr[0, 1, 0]。
# 此次类推。

In [ ]:
# T转置：表示整个顺序颠倒，（2[0], 2[1], 2[2]）转换为（2[2], 2[1], 2[0]）。
# 相应的分析方法一样，就是内容替换。

In [6]:
arr.transpose(1,0,2)  


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [8]:

arr.T


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [9]:
arr.transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [7]:

arr.transpose(0,2,1)  


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Numpy的去重与重复函数

In [10]:
# 1.unique函数
#通过unique函数可以找出数组中的唯一值并返回已经排序的结果
arr = np.array([1,1,1,2,2,3,3,])
res = np.unique(arr)
print(res)#[1 2 3]

[1 2 3]


In [11]:
# 2.tile函数
#主要有两个参数，参数’A’指定重复的数组，
#参数’reps’指定重复的次数
arr1 = np.arange(5)
arr2 = np.tile(arr1,3)
print(arr2)#[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]

[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [12]:
# 3.repeat函数
# numpy.repeat(a, repeats, axis=None)
# repeat 函数主要有三个参数，参数“a”是需要重复的数组元素，参数“repeats”是重复次数，
# 参数“axis”指定沿着哪个轴进行重复，axis = 0 表示按行进行元素重复；
# axis =1 表示按列进行元素重复

In [13]:
#def repeat(a,repeats,axis=None):
#axis=1表示按列进行元素重复
arr2 = np.random.randint(0,10,size=(3,3))
print('arr2:\n',arr2)
'''
arr2:
 [[5 0 0]
 [2 4 9]
 [7 8 1]]
'''
arr2_2_0 = np.repeat(arr2,2,axis=0)
print('按行进行重复',arr2_2_0)
'''
按行进行重复 [[5 0 0]
             [5 0 0]
             [2 4 9]
             [2 4 9]
             [7 8 1]
             [7 8 1]]
'''
rr2_2_1 = np.repeat(arr2,2,axis=1)
print('按列进行重复',arr2_2_0)
'''
按列进行重复 [[5 0 0]
             [5 0 0]
             [2 4 9]
             [2 4 9]
             [7 8 1]
             [7 8 1]]
'''




arr2:
 [[0 1 9]
 [3 8 7]
 [9 0 5]]
按行进行重复 [[0 1 9]
 [0 1 9]
 [3 8 7]
 [3 8 7]
 [9 0 5]
 [9 0 5]]
按列进行重复 [[0 1 9]
 [0 1 9]
 [3 8 7]
 [3 8 7]
 [9 0 5]
 [9 0 5]]


'\n按列进行重复 [[5 0 0]\n             [5 0 0]\n             [2 4 9]\n             [2 4 9]\n             [7 8 1]\n             [7 8 1]]\n'

In [16]:
# repeat和tile两个函数的区别：两个函数都能够对数组进行“重复”区别在于：
# tile函数是将数组进行重复，repeat函数是对元素进行重复

In [14]:
arr2_tile = np.tile(arr2,3)
print(arr2_tile)
'''

repeat重复555000000
tile500500500
发现区别了吧
'''

[[0 1 9 0 1 9 0 1 9]
 [3 8 7 3 8 7 3 8 7]
 [9 0 5 9 0 5 9 0 5]]


'\n[[5 0 0 5 0 0 5 0 0]\n [2 4 9 2 4 9 2 4 9]\n [7 8 1 7 8 1 7 8 1]]\n\nrepeat重复555000000\ntile500500500\n发现区别了吧\n'

In [ ]:
'''

repeat重复555000000
tile500500500
发现区别了吧
'''

# 伪随机数生成

In [ ]:
# numpy.random模块提供了很多生成随机数的函数，可以选择生成符合某种概率分布的随机数。
# 比如我们可以用normal得到一个4 x 4的，符合标准正态分布的数组

In [17]:
import numpy as np
samples = np.random.normal(size=(4, 4))
samples


array([[ 0.45818877, -0.155975  ,  0.9506864 ,  0.67779372],
       [-0.55200637, -1.26454116,  0.12433951,  0.14164555],
       [-1.03800391,  2.21212474,  2.15135375, -1.37511538],
       [ 0.37335657,  1.18013803, -0.21481957, -0.68121694]])

In [ ]:
# 相对的，python内建的random模块一次只能生成一个样本。
# 在生成大量样本方法numpy.random是非常快的。

In [18]:
from random import normalvariate
N = 1000000

%timeit sample = [normalvariate(0, 1) for _ in range(N)]
# 1 loop, best of 3: 1.25 s per loop

%timeit np.random.normal(size=N)
# 10 loops, best of 3: 49.1 ms per loop

1.11 s ± 94.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
34.5 ms ± 181 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 计算特征值和特征向量

In [ ]:
# 特征值和特征向量
# 特征值就是方程Ax=ax的根, 是一个标量

# 特征向量是关于特征值的向量

# Key_Function
# np.linalg.eigvals函数, 计算矩阵的特征值

# np.linalg.eig函数, 返回包含特征值和对应的特征向量的元组

In [19]:
import numpy as np

A = np.mat("1 -2 1; 0 2 -8; -4 5 9")
print(A)


[[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]


In [20]:
b = np.array([0, 8, -9])
print(b)


[ 0  8 -9]


In [21]:
x = np.linalg.solve(A, b)
print(x)


[29. 16.  3.]


In [22]:

print(np.dot(A, x))


[[ 0.  8. -9.]]
