In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
a = 2

In [3]:
dist = neighbors.DistanceMetric.get_metric('euclidean')
x = [[0, 1, 2],
     [3, 4, 5],
     [3, 7, 5],
     [0, 4, 1]]

In [4]:
dist.pairwise(x)

array([[0.        , 5.19615242, 7.34846923, 3.16227766],
       [5.19615242, 0.        , 3.        , 5.        ],
       [7.34846923, 3.        , 0.        , 5.83095189],
       [3.16227766, 5.        , 5.83095189, 0.        ]])

In [5]:
dist2 = neighbors.DistanceMetric.get_metric("manhattan")
dist2.pairwise(x)

array([[ 0.,  9., 12.,  4.],
       [ 9.,  0.,  3.,  7.],
       [12.,  3.,  0., 10.],
       [ 4.,  7., 10.,  0.]])

In [6]:
df = pd.DataFrame(x)

In [7]:
df

0  1  2
0  0  1  2
1  3  4  5
2  3  7  5
3  0  4  1

In [8]:
df.loc[[0],[0]]

0
0  0

In [9]:
# 只有一个参数默认取列
df[[1]]

1
0  1
1  4
2  7
3  4

In [10]:
# 先1列，后2行。顺序进行。反过来的矩阵
print(df[1][2])

# 二行一列
df[2:3][[1]]

7


1
2  7

In [11]:
df.values.ravel()

array([0, 1, 2, 3, 4, 5, 3, 7, 5, 0, 4, 1], dtype=int64)

In [12]:
arr1 = np.arange(25)

In [13]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
# 当为负数时，会直接考虑非负那一位，再自动求出另一位
print(arr1.reshape(-1,5)) # 多少行不知道，但每列有5个
print(arr1.reshape(5,-1)) #  多少列不知道，但每行有5个

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
