In [20]:
import numpy as np
import pandas as pd

# NumPy标准数据类型

1.1 题目：观察下列数据，请创建一个数组包含一下所有数据，并且要保证花费内存最小，同时输出对象占用的字节数
```
数据： 141,2,3,46,4,5,31,10
```
- 知识点：
    - numpy数组的创建
    - numpy的基本数据类型

In [6]:
solve1 = np.array([141, 2, 3, 46, 4, 5, 312, 10], dtype='uint8')
solve1.nbytes

8

# NumPy数组基础

2.1 题目：请使用切片方式，不使用临时变量，将下面二维数组进行转置
```py
np.random.seed(42)
solve2 = np.random.randint(0,101,(5,5),dtype='int8')
```
- 知识点：
    - 切片的使用
    - 切片后不是拷贝的理解
    - 异或的使用

In [79]:
np.random.seed(42)
solve2 = np.random.randint(0, 101, (5, 5), dtype='int8')
print(solve2)
print()
for i in range(solve2.shape[0]-1):
    # 注意，这里要为i+1，而不是1，因为行和列公用[n,n]上的值
    solve2[i, i+1:solve2.shape[1]] = solve2[i, i +
                                            1:solve2.shape[1]] ^ solve2[i+1:solve2.shape[0], i]
    solve2[i+1:solve2.shape[0], i] = solve2[i, i +
                                            1:solve2.shape[1]] ^ solve2[i+1:solve2.shape[0], i]
    solve2[i, i+1:solve2.shape[1]] = solve2[i, i +
                                            1:solve2.shape[1]] ^ solve2[i+1:solve2.shape[0], i]
print(solve2)

[[92 97 95 51 61]
 [75 92  3 98 14]
 [21 46 99 59 71]
 [84 25 71 60 46]
 [65 25 20 44 75]]

[[92 75 21 84 65]
 [97 92 46 25 25]
 [95  3 99 71 20]
 [51 98 59 60 44]
 [61 14 71 46 75]]


# NumPy数组的计算：通用函数

3.1 题目 使用np通用函数计算 ((A+B)*(-B/2))
```py
A = np.ones(3) * 1
B = np.ones(3) * 1
```

In [19]:
A = np.ones(3) * 1
B = np.ones(3) * 1
np.multiply(np.add(A,B),np.divide(-B,2))

array([-1., -1., -1.])

# numpy高级的通用函数特性

4.1 题目：对于一个小数组，用比 np.sum更快的方式对其求和
```py
# 数据：
solve4 = np.random.randint(5,size=(6,))
```
- 知识点：
    - 聚合函数

In [14]:
solve4 = np.random.randint(5, size=(6,))
np.add.reduce(solve4)

17

# 聚合：最小值、最大值和其他值

5.1 题目：请返回和最小的列
```py
# 数据
np.random.randint(0,100,(5,5))
```
- 知识点
    - 多维聚合
    - 聚合函数的使用

In [22]:
np.random.seed(42)
solve5 = np.random.randint(0, 100, (5, 5))
np.argmin(solve5.sum(axis=1))

4

# 数组的计算：广播

6.1题目：请用切片取出下方数据中心9个数
```py
# 数据
np.random.seed(42)
solve6 = np.random.randint(1,100,size=[5,5])
```

In [34]:
np.random.seed(42)
solve6 = np.random.randint(1, 100, size=[5, 5])
print(solve6)

solve6[np.arange(1, 4).reshape(3, 1), np.arange(1, 4).reshape(1, 3)]
# 或者：solve6[np.arange(1,4).reshape(1,3),np.arange(1,4).reshape(3,1)]

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]


array([[83, 87, 75],
       [24,  3, 22],
       [88, 30, 38]])

# 比较、掩码和布尔逻辑

7.1题目；给定一个数组[2,5,1,5,3,7,1],请把当中的偶数以及3-6之间元素取反

In [45]:
solve7 = np.array([2, 5, 1, 5, 3, 7, 1])
solve7[solve7 % 2 == 0 | ((solve7 > 3) & (solve7 < 6))] *= -1
print(solve7)

[-2 -5  1 -5  3  7  1]


# 花哨的索引

8.1题目：取出下列数据的删除头尾的第二、倒数第二行的倒序

In [76]:
np.random.seed(52)
solve8 = np.random.randint(1, 100, (5, 5))
print(solve8, end="\n\n")
print(solve8[[1, -2], -2:0:-1])

[[29 12 14 24 87]
 [29 33 70 12 92]
 [36 98 34  6 17]
 [12 55 47 43 62]
 [46 80 55 77 64]]

[[12 70 33]
 [43 47 55]]


# 数组的排序

9.1 题目：如何通过第1列对下列数据进行排序? 
```py
np.random.seed(42)
Z = np.random.randint(0,10,(3,3))
```

In [77]:
np.random.seed(42)
Z = np.random.randint(0, 10, (3, 3))
print(Z)
print(Z[Z[:, 1].argsort()])

[[6 3 7]
 [4 6 9]
 [2 6 7]]
[[6 3 7]
 [4 6 9]
 [2 6 7]]


# 结构化数据：NumPy的结构化数组

10.1 题目:请将下列四个人的数据保存到一个结构化数组中
```py
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
````

In [8]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
                          'formats': ('U10', 'i4', 'f8')})

data['name'] = name
data['age'] = age
data['weight'] = weight
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

# 数组的转置和轴对换

11.1 题目：请写出数组转置的三种方法
```

```

# Numpy的去重与重复函数

12.1 题目：计算下面两个数组总有多少个互不相同的数
```py
np.random.seed(42)
arr1 = np.random.randint(1,100,(50,))

np.random.seed(24)
arr2 = np.random.randint(1,100,(50,))
```

In [17]:
np.random.seed(42)
arr1 = np.random.randint(1,100,(50,))

np.random.seed(24)
arr2 = np.random.randint(1,100,(50,))

np.unique(np.concatenate((arr1,arr2),axis=0)).shape[0]

65

# 伪随机数生成