| 格式符|	说明|
|:--:|:--:|
| %a	|星期的英文单词的缩写：如星期一， 则返回 Mon|
| %A	|星期的英文单词的全拼：如星期一，返回 Monday|
| %b	|月份的英文单词的缩写：如一月， 则返回 Jan|
| %B	|月份的引文单词的缩写：如一月， 则返回 January|
| %c	|返回datetime的字符串表示，如03/08/15 23:01:26|
| %d	|返回的是当前时间是当前月的第几天|
| %f	|微秒的表示： 范围: [0,999999]|
| %H	|以24小时制表示当前小时|
| %I	|以12小时制表示当前小时|
| %j	|返回 当天是当年的第几天 范围[001,366]|
| %m	|返回月份 范围[0,12]|
| %M	|返回分钟数 范围 [0,59]|
| %P	|返回是上午还是下午–AM or PM|
| %S	|返回秒数 范围 [0,61]。。。手册说明的|
| %U	|返回当周是当年的第几周 以周日为第一天|
| %W	|返回当周是当年的第几周 以周一为第一天|
| %w	|当天在当周的天数，范围为[0, 6]，6表示星期天|
| %x	|日期的字符串表示 ：03/08/15|
| %X	|时间的字符串表示 ：23:22:08|
| %y	|两个数字表示的年份 15|
| %Y	|四个数字表示的年份 2015|
| %z	|与utc时间的间隔 （如果是本地时间，返回空字符串）|
| %Z	|时区名称（如果是本地时间，返回空字符串）|

In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
# 获得时间序列
# 该类型为datetimeIndex,可以直接赋值给index
datetime = pd.date_range(
    start="2018-06-01", end="2018-07-01",  freq=pd.offsets.BDay(3))
print(type(datetime))
datetime

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


DatetimeIndex(['2018-06-01', '2018-06-06', '2018-06-11', '2018-06-14',
               '2018-06-19', '2018-06-22', '2018-06-27'],
              dtype='datetime64[ns]', freq='3B')

In [4]:
df1 = pd.DataFrame(np.random.uniform(10, 50, (100, 1)),
                   index=pd.date_range("20170601", periods=100))
df1

0
2017-06-01  10.789465
2017-06-02  49.907913
2017-06-03  21.700034
2017-06-04  36.685301
2017-06-05  19.278807
...               ...
2017-09-04  16.129556
2017-09-05  41.650469
2017-09-06  30.482275
2017-09-07  32.074206
2017-09-08  36.361847

[100 rows x 1 columns]

In [5]:
# 得到的就是一个分组对象
resample = df1.resample("M")
resample

In [6]:
resample.mean()

0
2017-06-30  30.798333
2017-07-31  30.765744
2017-08-31  28.743877
2017-09-30  29.133732

In [7]:
df2 = pd.DataFrame(np.arange(25).reshape(5, 5))

In [8]:
df2

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [9]:
%who

autopep8	 datetime	 df1	 df2	 json	 np	 pd	 plt	 resample	 



In [10]:
pd.to_datetime(["2019-06-01"])

DatetimeIndex(['2019-06-01'], dtype='datetime64[ns]', freq=None)

In [11]:
# 返回DatatimeIndex
pd.to_datetime(["2019|06|01"], format="%Y|%m|%d")

DatetimeIndex(['2019-06-01'], dtype='datetime64[ns]', freq=None)

In [12]:
df3 = pd.DataFrame({'类别': ['水果', '水果', '水果', '蔬菜', '蔬菜', '肉类', '肉类'],
                    '产地': ['美国', '中国', '中国', '中国', '新西兰', '新西兰', '美国'],
                    '水果': ['苹果', '梨', '草莓', '番茄', '黄瓜', '羊肉', '牛肉'],
                    '数量': [5, 5, 9, 3, 2, 10, 8],
                    '价格': [5, 5, 10, 3, 3, 13, 20]})
df3

类别   产地  水果  数量  价格
0  水果   美国  苹果   5   5
1  水果   中国   梨   5   5
2  水果   中国  草莓   9  10
3  蔬菜   中国  番茄   3   3
4  蔬菜  新西兰  黄瓜   2   3
5  肉类  新西兰  羊肉  10  13
6  肉类   美国  牛肉   8  20

In [13]:
# 透视表是按照指定列重新分组，其他默认进行mean操作
df3.pivot_table(index=['产地', '类别'])

价格  数量
产地  类别          
中国  水果   7.5   7
    蔬菜   3.0   3
新西兰 肉类  13.0  10
    蔬菜   3.0   2
美国  水果   5.0   5
    肉类  20.0   8

In [14]:
# 将透视表指定为计数操作
df3.pivot_table(index=["产地", "类别"], aggfunc="count")

价格  数量  水果
产地  类别            
中国  水果   2   2   2
    蔬菜   1   1   1
新西兰 肉类   1   1   1
    蔬菜   1   1   1
美国  水果   1   1   1
    肉类   1   1   1

In [15]:
# 交叉表，即将指定为计数操作的透视表，一个作为index，一个作为column
pd.crosstab(df3["类别"], df3["产地"], margins=True)

产地   中国  新西兰  美国  All
类别                   
水果    2    0   1    3
肉类    0    1   1    2
蔬菜    1    1   0    2
All   3    2   2    7

In [16]:
%whos

Variable   Type                      Data/Info
----------------------------------------------
autopep8   module                    <module 'autopep8' from '<...>e-packages\\autopep8.py'>
datetime   DatetimeIndex             DatetimeIndex(['2018-06-0<...>tetime64[ns]', freq='3B')
df1        DataFrame                                     0\n20<...>n\n[100 rows x 1 columns]
df2        DataFrame                     0   1   2   3   4\n0 <...>19\n4  20  21  22  23  24
df3        DataFrame                    类别   产地  水果  数量  价格\n0<...>3\n6  肉类   美国  牛肉   8  20
json       module                    <module 'json' from 'D:\\<...>\lib\\json\\__init__.py'>
np         module                    <module 'numpy' from 'D:\<...>ges\\numpy\\__init__.py'>
pd         module                    <module 'pandas' from 'D:<...>es\\pandas\\__init__.py'>
plt        module                    <module 'matplotlib' from<...>matplotlib\\__init__.py'>
resample   DatetimeIndexResampler    DatetimeIndexResampler [f<...>=s

In [17]:
print(df2)
np1 = np.arange(25).reshape(5, 5)
print(np1)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
# numpy切片 和 pandas的 loc,iloc，是用一个中括号扩住
# pandas切片是两个中括号
print(np1[1:3, 1:3], end="\t\n"+"*"*20+"\t\n")
print(df2.loc[:, [2, 3, 4]], end="\t\n"+"*"*20+"\t\n")
print(df2[1:3][[0, 2]], end="\t\n"+"*"*20+"\t\n")

[[ 6  7]
 [11 12]]	
********************	
    2   3   4
0   2   3   4
1   7   8   9
2  12  13  14
3  17  18  19
4  22  23  24	
********************	
    0   2
1   5   7
2  10  12	
********************	


In [25]:
np1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
np1[[1, 2, 3], [1, 2, 3]]

array([ 6, 12, 18])

In [30]:
# 会发生广播
# (3,1),(3,)
# 广播成(3,3)
# 顺序按照索引指定的
np1[
    [[1],[3],[2]],
    [1, 2, 3]
   ]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])