In [1]:
import numpy as np
import pandas as pd
import csv

In [3]:
arr1 = np.arange(3)
arr2 = [i+3 for i in range(3)]
np.meshgrid(arr1,arr2)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]), array([[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])]

In [4]:
np.empty([5,5])

array([[  8.24969877e-312,   8.24975695e-312,   8.24969869e-312,
          8.24970051e-312,   8.24975010e-312],
       [  8.24975760e-312,   8.24973304e-312,   8.24975693e-312,
          8.24975760e-312,   8.24975694e-312],
       [  8.24975723e-312,   8.24969874e-312,   8.24975744e-312,
          8.24975279e-312,   8.24975694e-312],
       [  8.24975760e-312,   8.24973395e-312,   8.25020298e-312,
          8.24972424e-312,   8.25019830e-312],
       [  8.24973395e-312,   8.25019830e-312,   8.24972424e-312,
          8.25020281e-312,   8.24972477e-312]])

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.sqrt([1,2,3,4])

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [7]:
np.dot([1,2],[3,4])

11

In [8]:
arr1 = np.arange(25).reshape(5,5)

In [9]:
for i in arr1:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [10]:
arr1.shape

(5, 5)

In [11]:
np.array(arr2).shape[0]

3

In [12]:
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr1.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [14]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr1.std()

7.2111025509279782

In [16]:
np.power([1,2,3],[1,2,3])

array([ 1,  4, 27], dtype=int32)

In [17]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,np.ones([3,1])))

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.]])

In [2]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [3]:
data.iloc[1]

area      695662
pop     26448193
Name: Texas, dtype: int64

In [9]:
data.stack().unstack(level=0)

California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135